version: '3.8'
services:
  php: &default
    image: phpunit:latest
    build:
      context: .
      target: base
    working_dir: /application
    volumes:
      - .:/application
    command: sh -c ''
  tests:
    <<: *default
    command: sh -c './vendor/bin/phpunit tests/ProductDBTest.php --bootstrap=tests/bootstrap.php'