version: '3.8'
services:
  php: &default
    image: phpunit:latest
    build:
      context: .
      target: base
    working_dir: /application
    volumes:
      - .:/application
    command: sh -c 'sleep 86400'
  tests:
    <<: *default
    command: sh -c './vendor/bin/phpunit tests'
